# Generated by Django 5.1.2 on 2024-11-08 23:44
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_page_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="content",
            field=models.TextField(),  # Usa TextField como reemplazo
        ),
    ]
