# Generated by Django 5.1.2 on 2024-11-09 00:04

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_alter_page_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="content",
            field=django_quill.fields.QuillField(),
        ),
    ]
