# Generated by Django 5.1.2 on 2024-11-01 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 1, 14, 28, 45, 465435, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
